image: karlrun/java-node-gradle
stages:
  - test
  - build_ui
  - build_proxy

.build_ui_template: &build_ui_definition
  stage: build_ui
  script:
    - sh ./tasks/build_ui.sh
  artifacts:
    paths:
      - subtool-$CI_ENVIRONMENT_SLUG.tar.gz
    expire_in: 2 days

.build_proxy_template: &build_proxy_definition
  stage: build_proxy
  script:
    - sh ./tasks/build_proxy.sh
  artifacts:
    paths:
      - proxy/build/libs/proxy-$CI_ENVIRONMENT_SLUG.war
    expire_in: 2 days

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: test
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 2 days

test:
  stage: test
  variables:
    NODE_ENV: test
  script:
    - npm test
  only:
    - master@ndiaz/BioStudyUISub

build_ui_dev:
  <<: *build_ui_definition
  environment: DEV

build_ui_beta:
  <<: *build_ui_definition
  environment: BETA

build_ui_prod:
  <<: *build_ui_definition
  environment: PROD

build_proxy_dev:
  <<: *build_proxy_definition
  environment: DEV

build_proxy_beta:
  <<: *build_proxy_definition
  environment: BETA

build_proxy_prod:
  <<: *build_proxy_definition
  environment: PROD
