image: karlrun/java-node-gradle
stages:
  - test
  - build_ui
  - build_proxy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: test
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 2 days

test:
  stage: test
  variables:
    NODE_ENV: test
  script:
    - npm test
  only:
    - master@ndiaz/BioStudyUISub

build_ui:
  stage: build_ui
  script:
    - npm run build
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - subtool.tar.gz
    expire_in: 2 days

build_proxy:
  stage: build_proxy
  script:
    - npm run build:proxy
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - build/libs/proxy.war
    expire_in: 2 days
