image: thompsnm/nodejs-chrome:latest
stages:
  - test
  - build

install_dependencies:
  stage: test
  script:
    - npm install

unit_test:
  stage: test
  variables:
    NODE_ENV: test
  before_script:
    - npm install
  script:
    - npm test
  only:
    - master@ndiaz/BioStudyUISub

build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - artifacts/subtool.tar.gz
    expire_in: 1 day
