image: thompsnm/nodejs-chrome:latest
stages:
  - test
  - build

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: test
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 2 days

test:
  stage: test
  variables:
    NODE_ENV: test
  script:
    - npm test
  only:
    - master@ndiaz/BioStudyUISub

build:
  stage: build
  script:
    - npm run build
  artifacts:
    name: $CI_JOB_NAME
    paths:
      - subtool.tar.gz
    expire_in: 2 days

build_proxy:
  image: openjdk:latest
  stage: build
  script:
    - npm run build:proxy
