image: node:14.17.5
variables:
  DOCKER_TLS_CERTDIR: ''
stages:
  - setup
  - test
  - build
  - build_image
  - deploy

.build_template: &build_template
  stage: build
  before_script:
    - sh ./tasks/build_setup.sh
  script:
    - sh ./tasks/build.sh
  artifacts:
    paths:
      - subtool-$CI_ENVIRONMENT_SLUG.tar.gz
    expire_in: 2 days

.build_image: &build_image_template
  stage: build_image
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - sh ./tasks/build_image.sh

.deploy_template: &deploy_definition
  stage: deploy
  before_script:
    - sh ./tasks/ssh_setup.sh
  script:
    - sh ./tasks/deploy.sh

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: setup
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 2 days

test:
  stage: test
  dependencies:
    - install_dependencies
  variables:
    NODE_ENV: test
  script:
    - npm test
    - npm run ng build --dry-run

on-pull-requests:
  dependencies:
    - install_dependencies
  variables:
    NODE_ENV: test
  script:
    - npm test
    - npm run ng build --dry-run
  only:
    - external_pull_requests

# Build per environment
build:dev:
  <<: *build_template
  environment: DEV
  only:
    - dev@ndiaz/BioStudyUISub

build:beta:
  <<: *build_template
  environment: BETA
  only:
    - beta@ndiaz/BioStudyUISub

build:sandbox:
  <<: *build_template
  environment: SANDBOX
  only:
    - master@ndiaz/BioStudyUISub

build:prod:
  <<: *build_template
  environment: PROD
  only:
    - master@ndiaz/BioStudyUISub

# Build Docker image per environment
build_image:prod:
  <<: *build_image_template
  environment: SANDBOX
  dependencies:
    - build:sandbox
  only:
    - master@ndiaz/BioStudyUISub
  when: manual

# Deploy per environment
deploy:dev:
  <<: *deploy_definition
  environment: DEV
  dependencies:
    - build:dev
  only:
    - dev@ndiaz/BioStudyUISub

deploy:beta:
  <<: *deploy_definition
  environment: BETA
  dependencies:
    - build:beta
  only:
    - beta@ndiaz/BioStudyUISub
  when: manual

deploy:prod:
  <<: *deploy_definition
  environment: PROD
  dependencies:
    - build:prod
  only:
    - master@ndiaz/BioStudyUISub
  when: manual
