branches:
  only:
    - dev

language: node_js

node_js:
  - "6"

install:
  - npm install
  - ./node_modules/.bin/jspm install

before_script:
  - ./node_modules/.bin/gulp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/gulp test
